Models/Utilisateur.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcTodo.Models
{
    public class Utilisateur
    {
        private int _id;
        private string _name;
        private string _password;

        public Utilisateur()
        {
        }

        public Utilisateur(string name, string password)
        {
            _name = name;
            _password = password;
        }

        public Utilisateur(int id, string name, string password)
        {
            _id = id;
            _name = name;
            _password = password;
        }

        public int Id { get => _id; set => _id = value; }
        public string Name { get => _name; set => _name = value; }
        public string Password { get => _password; set => _password = value; }

        public override bool Equals(object obj)
        {
            return obj is Utilisateur utilisateur &&
                   _name == utilisateur._name &&
                   _password == utilisateur._password;
        }

        public override int GetHashCode()
        {
            int hashCode = 1534016392;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(_name);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(_password);
            return hashCode;
        }
    }
}

Controllers/UtilisateurController.cs
using MvcTodo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TacheMVC.Controllers
{
    public class UtilisateurController : Controller
    {
        // GET: Utilisateur
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Inscription(Utilisateur utilisateur)
        {
            DBConnection.InsererUtilisateur(utilisateur);
            return RedirectToAction("Index");
        }
        public ActionResult Login(Utilisateur utilisateur)
        {
            if (DBConnection.Logutilisateur(utilisateur))
            {
                return RedirectToRoute("Accueil");
            }
            else
            {
                return RedirectToRoute("FirstPage");
            }
            
        }
    }
}

Views/Utilisateur/Index.cshtml
@model MvcTodo.Models.Utilisateur

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Accueil</h2>


@using (Html.BeginForm("Inscription","Utilisateur")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sign in" class="btn btn-default" />
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Login">
                   Log in
                </button>
            </div>
        </div>
    </div>
}

<div class="modal fade" id="Login">
    <div class="modal-dialog" >
        <div class="modal-content">
            <div class="modal-header">
                
                <h4 class="modal-title">Tache à faire</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Login", "Utilisateur"))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Authentification</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Log in" class="btn btn-primary" />



                            </div>
                        </div>
                    </div>
                }
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                </div>
            </div>
        </div>
    </div>
</div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }