Models/Tache.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcTodo.Models
{
    public class Tache
    {
        private int _tacheid;
        private string _username;
        private string _desription;
        private bool _state;


        public string Username { get => _username; set => _username = value; }
        public string Desription { get => _desription; set => _desription = value; }
        public bool State { get => _state; set => _state = value; }
        public int Tacheid { get => _tacheid; set => _tacheid = value; }

        public Tache(string username, string desription, bool state)
        {
            _username = username;
            _desription = desription;
            _state = state;
        }

        public Tache(int tacheid, string username, string desription, bool state)
        {
            _tacheid = tacheid;
            _username = username;
            _desription = desription;
            _state = state;
        }

        public Tache()
        {
        }
    }
}

Controllers/TacheController.cs
using MvcTodo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcTodo.Controllers
{
    public class TacheController : Controller
    {
        // GET: Tache
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Tachelist()
        {
            //DBconnection.listetache(Session["username"].ToString())
            if (Session["username"] != null)
            {
                return View(DBConnection.listetache(Session["username"].ToString()));
            }
            else
            {
                return RedirectToRoute("Accueil");
            }

        }

        public ActionResult Supprimer(int Tacheid)
        {
            DBConnection.SuppresionTache(Tacheid);
            return RedirectToRoute("Accueil");
        }

        // GET: Tache/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Tache/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tache/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Tache/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Tache/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Tache/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Tache/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Tache/Tachelist.cshtml
@model IEnumerable<MvcTodo.Models.Tache>

@{
    ViewBag.Title = "Tachelist";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tachelist</h2>

<p>
    <input type="button" class="btn btn-primary" data-toggle="modal" data-target="#addtask" value="Ajouter" />
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Desription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td id="description_@item.Tacheid">
                @Html.DisplayFor(modelItem => item.Desription)
            </td>
            <td id="state_@item.Tacheid">
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.ActionLink("Modifier", "Modifier", new { id = item.Tacheid }) |

                @Html.ActionLink("Supprimer", "Supprimer", new { id = item.Tacheid })
            </td>
        </tr>
    }

    <div class="modal fade" id="addtask">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Tache à faire</h4>
                </div>
                @using (Html.BeginForm("Create", "Tache"))
                {
                    @Html.AntiForgeryToken()
                    <div class="modal-body">


                        <div class="form-group">
                            <div class="col-md-10">
                                <input type="text" name="description" value="" class="form-control" />
                            </div>
                        </div>

                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                        <button type="submit" class="btn btn-primary">Ajouter</button>
                    </div>


                }
            </div>
        </div>
    </div>

</table>